### ISSUE TITLE
LazyHGrid doesn't render emoji list fast enough

### ISSUE THREAD

**Issue by apourgol** [mpetrenco/EmojiPicker#2] opened 2024-10-09 01:20 UTC
Hi, hope you're doing well.
I love your design and am incorporating it into my own project, however I've found a small issue with it:

1) The horizontal scroll fairs well if I scroll through the emoji list slowly, although slightly choppy if you pay enough attention.
2) Catergory scrollTo is also affected by this. Scrolling to another category is also very choppy.

Do you think there is any way to address this?

**Comment by mpetrenco** [comment] 2024-10-09 11:28
Hi @apourgol,
The only solution I can think of is replacing the whole `LazyHGrid` with a proper `UICollectionView` so that we can use reusable cell identifiers, which should probably solve the performance issue.

I'll play around with it and let you know how it goes.

**Comment by mpetrenco** [comment] 2024-10-09 18:48
My assumption was right - replacing the grid with a collection view did fix the performance issues.
@apourgol please check version `2.1.1` and let me know if that's ok with you.

Side Note: As a bonus I also added haptic feedback when selecting an emoji / category.

**Comment by apourgol** [comment] 2024-10-09 18:57
Hi Mihai,

Version 2.1.1 is perfect in terms of scrolling smoothly and jumping from category to category. I'd consider the issue fixed.

As for the haptic feedback, I like the idea of it. However, it only works when I press down hard and hold it for a while. Is there any way to make it a single tap with haptic feedback?

Thanks,
Amin

**Comment by mpetrenco** [comment] 2024-10-09 19:40
Glad it worked out. 
Regarding the haptic feedback, I can't seem to reproduce it on my side on a clean app.

The code for this is literally _this_ added on a tap action:

```swift
let generator = UIImpactFeedbackGenerator(style: .medium)
generator.impactOccurred()
```

I'll close this issue, since it's fixed, but I'll keep an eye out for the haptic issue.

**Closed as completed by mpetrenco** 2024-10-09 19:40 UTC
Labels: enhancement

**Comment by apourgol** [comment] 2024-10-09 20:15
It's weird, the categories change and produce the haptic feedback with a single click/tap perfectly. It's just selecting the emojis that's now harder.

I tested it both on my physical device and on a simulator. Both are harder to tap on individual emojis. I'll test it on a clean app too and give you an update.

**Comment by apourgol** [comment] 2024-10-09 23:49
So, turns out having my gestures to hide the keyboard before the .emojipicker(isDiplayed:onEmojiSelected:) was causing the issue. Everything works perfectly now.

Thanks for the amazing library!
